import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Heart, Clock, MapPin, Music, Sparkles, Share2, Calendar, Download, PartyPopper, Utensils, ExternalLink, Phone, Globe, RefreshCw, MessageCircle, Lightbulb, Shield, Map } from "lucide-react";
import DatePlanMap from "../map/DatePlanMap";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { DatePlan } from "@/entities/DatePlan";
import SharePlanDialog from "../collaboration/SharePlanDialog";
import CollaborativeNotes from "../collaboration/CollaborativeNotes";
import ActivityVoting from "../collaboration/ActivityVoting";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger
} from "@/components/ui/collapsible";

export default function DatePlanResults({ plan: initialPlan, onPlanAnother, onRegenerate }) {
  const [showConfetti, setShowConfetti] = useState(true);
  const [plan, setPlan] = useState(initialPlan);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const currencySymbol = plan.currency_symbol || '$';

  const refreshPlan = async () => {
    setIsRefreshing(true);
    try {
      const updated = await DatePlan.get(plan.id);
      setPlan(updated);
    } catch (error) {
      console.error('Error refreshing plan:', error);
    } finally {
      setIsRefreshing(false);
    }
  };

  const sharePlan = async () => {
    const locationText = plan.location ? ` in ${plan.location}` : '';
    const shareText = `Check out this amazing date plan${locationText}: ${plan.title}\n\nGenerated by PerfectDate`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: plan.title,
          text: shareText,
          url: window.location.origin
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Plan details copied to clipboard!');
    }
  };

  const downloadPlan = () => {
    const planText = `
${plan.title}
${plan.is_surprise ? '✨ Surprise Date!' : ''}

Budget: ${currencySymbol}${plan.total_cost}
Time: ${plan.time_of_day}
${plan.location ? `Location: ${plan.location}` : ''}

ITINERARY:
${plan.itinerary.map((item) =>
  `${item.time} - ${item.activity}
  Location: ${item.location}
  Cost: ${currencySymbol}${item.cost}
  ${item.insider_tip ? `Insider Tip: ${item.insider_tip}` : ''}`
).join('\n')}

Playlist Suggestion: ${plan.playlist_suggestion}

Special Notes: ${plan.special_notes}

Generated by PerfectDate
    `;

    const blob = new Blob([planText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${plan.title.replace(/[^a-zA-Z0-9]/g, '_')}_date_plan.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen py-12 relative overflow-hidden">
      {/* Confetti Animation */}
      {showConfetti &&
        <div className="fixed inset-0 pointer-events-none z-10">
          {[...Array(50)].map((_, i) =>
            <motion.div
              key={i}
              className="absolute w-3 h-3 bg-gradient-to-r from-pink-500 to-purple-500 rounded-full"
              initial={{ x: Math.random() * window.innerWidth, y: -20, rotation: 0 }}
              animate={{ y: window.innerHeight + 20, rotation: 360 }}
              transition={{ duration: 3, delay: i * 0.1, ease: "linear" }}
              onAnimationComplete={() => i === 49 && setShowConfetti(false)}
            />
          )}
        </div>
      }

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}>

          {/* Header */}
          <div className="text-slate-50 mb-12 text-center">
            <div className="inline-flex items-center gap-2 bg-gradient-to-r from-pink-500 to-purple-500 text-white px-6 py-3 rounded-full mb-6">
              <Sparkles className="w-5 h-5" />
              <span className="font-semibold">
                {plan.is_surprise ? 'Surprise Date Generated!' : 'Your Perfect Date Plan'}
              </span>
            </div>

            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">{plan.title}</h1>

            <div className="flex items-center justify-center gap-6 text-gray-600 flex-wrap">
              <div className="flex items-center gap-2">
                <span className="font-semibold text-lg">{currencySymbol}{plan.total_cost} {plan.currency_code}</span>
              </div>
              <div className="flex items-center gap-2">
                <Clock className="w-5 h-5" />
                <span className="capitalize">{plan.time_of_day}</span>
              </div>
              {plan.location &&
                <div className="flex items-center gap-2">
                  <MapPin className="w-5 h-5" />
                  <span className="font-semibold text-pink-600">{plan.location}</span>
                </div>
              }
            </div>

            {plan.location &&
              <div className="mt-4 p-4 bg-gradient-to-r from-pink-50 to-purple-50 rounded-lg border border-pink-200">
                <p className="text-gray-700">
                  <MapPin className="w-4 h-4 inline mr-1 text-pink-500" />
                  This date plan is specifically curated for <strong>{plan.location}</strong> with local venue suggestions
                </p>
              </div>
            }
          </div>

          {/* What This Date Is Optimized For */}
          {plan.optimized_for &&
            <Card className="mb-6 shadow-lg border-none bg-gradient-to-br from-blue-50 to-indigo-50">
              <CardContent className="pt-6">
                <div className="flex items-start gap-3">
                  <Heart className="w-5 h-5 text-blue-500 mt-1 flex-shrink-0" />
                  <div>
                    <h3 className="font-semibold text-gray-900 mb-2">What this date is optimized for</h3>
                    <p className="text-gray-700 leading-relaxed">{plan.optimized_for}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          }

          {/* Why This Works */}
          {plan.why_this_works && plan.why_this_works.length > 0 &&
            <Card className="mb-8 shadow-lg border-none bg-gradient-to-br from-green-50 to-emerald-50">
              <CardContent className="pt-6">
                <div className="flex items-start gap-3">
                  <Lightbulb className="w-5 h-5 text-green-600 mt-1 flex-shrink-0" />
                  <div className="flex-1">
                    <h3 className="font-semibold text-gray-900 mb-3">Why this works</h3>
                    <ul className="space-y-2">
                      {plan.why_this_works.map((reason, idx) =>
                        <li key={idx} className="flex items-start gap-2 text-gray-700">
                          <span className="text-green-600 mt-1">•</span>
                          <span>{reason}</span>
                        </li>
                      )}
                    </ul>
                  </div>
                </div>
              </CardContent>
            </Card>
          }

          {/* Collaborative Notes */}
          {plan.shared_with && plan.shared_with.length > 0 &&
            <div className="mb-8">
              <CollaborativeNotes plan={plan} onUpdate={refreshPlan} />
            </div>
          }

          {/* Interactive Map */}
          <Card className="mb-8 shadow-xl border-none bg-white/90 backdrop-blur-sm">
            <CardHeader>
              <CardTitle className="text-2xl font-bold text-gray-900 flex items-center gap-2">
                <Map className="w-6 h-6 text-pink-500" />
                Date Map
                {plan.location && <span className="text-base font-normal text-gray-600">in {plan.location}</span>}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <DatePlanMap plan={plan} />
            </CardContent>
          </Card>

          {/* Itinerary */}
          <Card className="mb-8 shadow-xl border-none bg-white/90 backdrop-blur-sm">
            <CardHeader>
              <CardTitle className="text-2xl font-bold text-gray-900 flex items-center gap-2">
                <Calendar className="w-6 h-6 text-pink-500" />
                Your Date Itinerary
                {plan.location && <span className="text-base font-normal text-gray-600">in {plan.location}</span>}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                {plan.itinerary.map((item, index) =>
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.6, delay: index * 0.1 }}
                    className="relative overflow-hidden rounded-xl border border-pink-100 group">

                    <div
                      className="absolute inset-0 bg-cover bg-center opacity-30 group-hover:opacity-40 transition-opacity duration-300"
                      style={{ backgroundImage: `url(https://source.unsplash.com/800x600/?${encodeURIComponent(item.activity.split(' ').slice(0, 3).join(','))},romantic,date)` }}
                    />
                    <div className="absolute inset-0 bg-gradient-to-r from-pink-50/95 to-purple-50/95 backdrop-blur-sm" />

                    <div className="relative flex items-start gap-4 p-4">
                      <div className="w-16 h-16 bg-gradient-to-r from-pink-500 to-purple-500 rounded-full flex items-center justify-center text-white font-bold flex-shrink-0 shadow-lg">
                        {index + 1}
                      </div>
                      <div className="flex-1">
                        {plan.shared_with && plan.shared_with.length > 0 &&
                          <div className="mb-3">
                            <ActivityVoting plan={plan} activityIndex={index} onUpdate={refreshPlan} />
                          </div>
                        }
                        <div className="flex items-center gap-2 mb-2">
                          <Clock className="w-4 h-4 text-pink-500" />
                          <span className="font-semibold text-pink-600">{item.time}</span>
                        </div>
                        <h3 className="text-lg font-bold text-gray-900 mb-2">{item.activity}</h3>
                        <div className="flex items-center gap-4 text-sm text-gray-600 mb-2">
                          <div className="flex items-center gap-1">
                            <MapPin className="w-4 h-4" />
                            <span className="font-medium">{item.location}</span>
                          </div>
                          <div className="flex items-center gap-1">
                            <span className="font-medium">{currencySymbol}{item.cost}</span>
                          </div>
                        </div>
                        {item.insider_tip &&
                          <div className="mt-2 p-2 bg-yellow-50 border border-yellow-200 rounded-lg">
                            <p className="text-sm text-yellow-800">
                              <span className="font-semibold">💡 Insider Tip:</span> {item.insider_tip}
                            </p>
                          </div>
                        }
                        {item.food_suggestions &&
                          <div className="mt-2 p-2 bg-green-50 border border-green-200 rounded-lg">
                            <p className="text-sm text-green-800">
                              <Utensils className="w-3 h-3 inline mr-1" />
                              <span className="font-semibold">Must Try:</span> {item.food_suggestions}
                            </p>
                          </div>
                        }
                        {(item.booking_url || item.phone_number || item.website) &&
                          <div className="mt-3 flex flex-wrap gap-2">
                            {item.booking_url &&
                              <a href={item.booking_url} target="_blank" rel="noopener noreferrer"
                                className="inline-flex items-center gap-1 px-3 py-1.5 bg-pink-500 hover:bg-pink-600 text-white text-sm rounded-lg transition-colors">
                                <Calendar className="w-3.5 h-3.5" />Book Now<ExternalLink className="w-3 h-3" />
                              </a>
                            }
                            {item.phone_number &&
                              <a href={`tel:${item.phone_number}`}
                                className="inline-flex items-center gap-1 px-3 py-1.5 bg-purple-500 hover:bg-purple-600 text-white text-sm rounded-lg transition-colors">
                                <Phone className="w-3.5 h-3.5" />Call
                              </a>
                            }
                            {item.website &&
                              <a href={item.website} target="_blank" rel="noopener noreferrer"
                                className="inline-flex items-center gap-1 px-3 py-1.5 bg-gray-600 hover:bg-gray-700 text-white text-sm rounded-lg transition-colors">
                                <Globe className="w-3.5 h-3.5" />Website<ExternalLink className="w-3 h-3" />
                              </a>
                            }
                          </div>
                        }
                      </div>
                    </div>
                  </motion.div>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Upcoming Events */}
          {plan.upcoming_events &&
            <Card className="mb-8 shadow-lg border-none bg-gradient-to-br from-purple-50 to-pink-50">
              <CardHeader>
                <CardTitle className="text-xl font-bold text-gray-900 flex items-center gap-2">
                  <PartyPopper className="w-5 h-5 text-purple-500" />
                  Special Events Happening
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-700 leading-relaxed">{plan.upcoming_events}</p>
              </CardContent>
            </Card>
          }

          {/* Special Features */}
          <div className="grid md:grid-cols-2 gap-6 mb-8">
            <Card className="shadow-lg border-none bg-gradient-to-br from-purple-50 to-pink-50">
              <CardHeader>
                <CardTitle className="text-xl font-bold text-gray-900 flex items-center gap-2">
                  <Music className="w-5 h-5 text-purple-500" />
                  Playlist Suggestion
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-700 leading-relaxed">{plan.playlist_suggestion}</p>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-none bg-gradient-to-br from-pink-50 to-purple-50">
              <CardHeader>
                <CardTitle className="text-xl font-bold text-gray-900 flex items-center gap-2">
                  <Heart className="w-5 h-5 text-pink-500" />
                  Special Touches
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-700 leading-relaxed">{plan.special_notes}</p>
              </CardContent>
            </Card>
          </div>

          {/* Optional Support Sections */}
          <div className="space-y-4 mb-8">
            {plan.conversation_prompts && plan.conversation_prompts.length > 0 &&
              <Collapsible>
                <Card className="shadow-md border-none bg-white">
                  <CollapsibleTrigger className="w-full">
                    <CardHeader className="hover:bg-gray-50 transition-colors cursor-pointer">
                      <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                        <MessageCircle className="w-5 h-5 text-purple-500" />
                        Conversation Lifelines
                        <Sparkles className="w-4 h-4 text-gray-400 ml-auto" />
                      </CardTitle>
                    </CardHeader>
                  </CollapsibleTrigger>
                  <CollapsibleContent>
                    <CardContent>
                      <ul className="space-y-2">
                        {plan.conversation_prompts.map((prompt, idx) =>
                          <li key={idx} className="flex items-start gap-2 text-gray-700">
                            <span className="text-purple-500 mt-1">•</span>
                            <span>{prompt}</span>
                          </li>
                        )}
                      </ul>
                    </CardContent>
                  </CollapsibleContent>
                </Card>
              </Collapsible>
            }

            {plan.backup_option &&
              <Collapsible>
                <Card className="shadow-md border-none bg-white">
                  <CollapsibleTrigger className="w-full">
                    <CardHeader className="hover:bg-gray-50 transition-colors cursor-pointer">
                      <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                        <RefreshCw className="w-5 h-5 text-blue-500" />
                        Backup Option
                        <Sparkles className="w-4 h-4 text-gray-400 ml-auto" />
                      </CardTitle>
                    </CardHeader>
                  </CollapsibleTrigger>
                  <CollapsibleContent>
                    <CardContent>
                      <p className="text-gray-700 leading-relaxed">{plan.backup_option}</p>
                    </CardContent>
                  </CollapsibleContent>
                </Card>
              </Collapsible>
            }

            {plan.reassurance_note &&
              <Collapsible>
                <Card className="shadow-md border-none bg-white">
                  <CollapsibleTrigger className="w-full">
                    <CardHeader className="hover:bg-gray-50 transition-colors cursor-pointer">
                      <CardTitle className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                        <Shield className="w-5 h-5 text-green-500" />
                        Reassurance Note
                        <Sparkles className="w-4 h-4 text-gray-400 ml-auto" />
                      </CardTitle>
                    </CardHeader>
                  </CollapsibleTrigger>
                  <CollapsibleContent>
                    <CardContent>
                      <p className="text-gray-700 leading-relaxed">{plan.reassurance_note}</p>
                    </CardContent>
                  </CollapsibleContent>
                </Card>
              </Collapsible>
            }
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <SharePlanDialog plan={plan} onShare={refreshPlan} />

            <Button onClick={sharePlan} variant="outline" className="border-2 border-pink-500 text-pink-600 hover:bg-pink-50 px-8 py-3 rounded-full">
              <Share2 className="w-5 h-5 mr-2" />Quick Share
            </Button>

            <Button onClick={downloadPlan} variant="outline" className="border-2 border-purple-500 text-purple-600 hover:bg-purple-50 px-8 py-3 rounded-full">
              <Download className="w-5 h-5 mr-2" />Download
            </Button>

            <Button onClick={refreshPlan} variant="outline" disabled={isRefreshing} className="border-2 border-gray-400 text-gray-600 hover:bg-gray-50 px-8 py-3 rounded-full">
              <RefreshCw className={`w-5 h-5 mr-2 ${isRefreshing ? 'animate-spin' : ''}`} />Refresh
            </Button>

            {onRegenerate && (
              <Button onClick={onRegenerate} variant="outline" className="border-2 border-purple-500 text-purple-600 hover:bg-purple-50 px-8 py-3 rounded-full">
                <RefreshCw className="w-5 h-5 mr-2" />Regenerate Plan
              </Button>
            )}

            <Button onClick={onPlanAnother} className="bg-gradient-to-r from-pink-500 to-purple-500 hover:from-pink-600 hover:to-purple-600 text-white px-8 py-3 rounded-full shadow-lg">
              <Sparkles className="w-5 h-5 mr-2" />Plan Another
            </Button>
          </div>

          {/* Link to Saved Plans */}
          <div className="text-center mt-8">
            <p className="text-gray-600 mb-4">Want to see all your date plans?</p>
            <Link to={createPageUrl("SavedPlans")}>
              <Button variant="ghost" className="text-pink-600 hover:text-pink-700">
                View My Saved Plans →
              </Button>
            </Link>
          </div>

        </motion.div>
      </div>
    </div>
  );
}