import React, { useState, useEffect } from "react";
import { DatePlan } from "@/entities/DatePlan";
import { User } from "@/entities/User";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Heart, Sparkles, Calendar, DollarSign, Trash2, Share2, Eye } from "lucide-react";
import { motion } from "framer-motion";
import { Link, useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";

export default function SavedPlans() {
  const navigate = useNavigate();
  const [savedPlans, setSavedPlans] = useState([]);
  const [user, setUser] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadSavedPlans();
  }, []);

  const loadSavedPlans = async () => {
    try {
      const currentUser = await User.me();
      setUser(currentUser);
      const plans = await DatePlan.filter({ created_by: currentUser.email }, '-created_date');
      setSavedPlans(plans);
    } catch (error) {
      console.error('Error loading saved plans:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const deletePlan = async (planId) => {
    try {
      await DatePlan.delete(planId);
      setSavedPlans(savedPlans.filter(plan => plan.id !== planId));
    } catch (error) {
      console.error('Error deleting plan:', error);
    }
  };

  const sharePlan = async (plan) => {
    const shareText = `Check out this amazing date plan: ${plan.title}\n\nGenerated by PerfectDate`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: plan.title,
          text: shareText,
          url: window.location.origin
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      // Fallback - copy to clipboard
      navigator.clipboard.writeText(shareText);
      alert('Plan details copied to clipboard!');
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen py-12 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-pink-500 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading your saved plans...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen py-12">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Your{" "}
            <span className="bg-gradient-to-r from-pink-600 to-purple-600 bg-clip-text text-transparent">
              Saved Plans
            </span>
          </h1>
          <p className="text-xl text-gray-600">
            Relive your favorite date memories and plan new adventures
          </p>
        </div>

        {savedPlans.length === 0 ? (
          <div className="text-center py-16">
            <div className="w-24 h-24 bg-gradient-to-r from-pink-500 to-purple-500 rounded-full flex items-center justify-center mx-auto mb-6 opacity-20">
              <Heart className="w-12 h-12 text-white" />
            </div>
            <h3 className="text-2xl font-semibold text-gray-900 mb-4">
              No saved plans yet
            </h3>
            <p className="text-gray-600 mb-8 max-w-md mx-auto">
              Start planning your perfect dates and they'll appear here for you to revisit anytime.
            </p>
            <Link to={createPageUrl("PlanDate")}>
              <Button className="bg-gradient-to-r from-pink-500 to-purple-500 hover:from-pink-600 hover:to-purple-600 text-white px-8 py-3 rounded-full">
                <Sparkles className="w-5 h-5 mr-2" />
                Plan Your First Date
              </Button>
            </Link>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {savedPlans.map((plan, index) => (
              <motion.div
                key={plan.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
              >
                <Card className="h-full shadow-lg hover:shadow-2xl hover:-translate-y-2 transition-all duration-200 group bg-white/80 backdrop-blur-sm border-pink-100">
                  <CardHeader className="pb-3">
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <CardTitle className="text-xl font-bold text-gray-900 mb-2 group-hover:text-pink-600 transition-colors">
                          {plan.title}
                        </CardTitle>
                        <div className="flex items-center gap-4 text-sm text-gray-600">
                          <div className="flex items-center gap-1">
                            <Calendar className="w-4 h-4" />
                            {plan.time_of_day}
                          </div>
                          <div className="flex items-center gap-1">
                            <span className="font-medium">{plan.currency_symbol || '$'}{plan.total_cost} {plan.currency_code || 'USD'}</span>
                          </div>
                        </div>
                      </div>
                      {plan.is_surprise && (
                        <div className="bg-gradient-to-r from-pink-500 to-purple-500 text-white px-2 py-1 rounded-full text-xs font-semibold">
                          Surprise!
                        </div>
                      )}
                    </div>
                  </CardHeader>
                  
                  <CardContent className="pt-0">
                    <div className="space-y-3 mb-4">
                      {plan.itinerary?.slice(0, 3).map((item, idx) => (
                        <div key={idx} className="flex items-start gap-3">
                          <div className="w-2 h-2 bg-pink-500 rounded-full mt-2 flex-shrink-0"></div>
                          <div className="flex-1">
                            <p className="font-medium text-gray-900 text-sm">{item.activity}</p>
                            <p className="text-xs text-gray-600">{item.time} • {item.location}</p>
                          </div>
                        </div>
                      ))}
                      {plan.itinerary?.length > 3 && (
                        <p className="text-xs text-gray-500 text-center">
                          +{plan.itinerary.length - 3} more activities
                        </p>
                      )}
                    </div>
                    
                    <div className="flex items-center justify-between pt-4 border-t border-gray-100">
                      <div className="flex gap-2">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => navigate(createPageUrl("ViewPlan") + `?id=${plan.id}`)}
                          className="text-gray-600 hover:text-purple-600"
                        >
                          <Eye className="w-4 h-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => sharePlan(plan)}
                          className="text-gray-600 hover:text-pink-600"
                        >
                          <Share2 className="w-4 h-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => deletePlan(plan.id)}
                          className="text-gray-600 hover:text-red-600"
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                      <p className="text-xs text-gray-500">
                        {new Date(plan.created_date).toLocaleDateString()}
                      </p>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}